### ISSUE TITLE
Name clash with already-existing app

### ISSUE THREAD

**Issue by therealbluepandabear** [LibreTubeApp/LibreTube#338]
There seems to be another app with the same name as this which was created after this one, I think this might be against GitHub's terms of service, you might want to consider looking into it ;)

**Comment by esphen** [comment]
@therealbluepandabear Thanks for the heads up! This project lies dormant as I lost interest in seeing it through, so so them taking the name is just fine. Better they use it for something useful than us squatting it 😄
